### ISSUE TITLE
Environment Configuration

### ISSUE THREAD

**Issue by 13XAVI** [atlp-rwanda/dynamites-ecomm-be#14]
#### Description

As a developer, I want to create an Envirnomental variable  file for the e-commerce project, providing crucial information about the project Declared Variable, its setup, and its status.

All Environmental Varables will help new contributors and stakeholders to  hide  Development Variables like Links,Ports,Secret-Keys in order to avoid  securitiy vurnerability isuues globally.

#### Tasks

- [ ] Create a dot env file in the root directory of the project repository
- [ ] Set up environment variables for different environments (e.g., development, staging, production)
- [ ] Use a tool like dotenv to manage environment variables
- [ ] Ensure  Sensitive Information in Dotenv  file are  never Pushed
- [ ] Add a Description on  Each environmental varable 

#### Developer Notes

- Follow best practices for Configuring clear and concise Dotenv file
- Use appropriate headings, formatting, and code snippets for better readability

#### Definition of Done

- The Dot env file is created in the project repository's root directory
- The Dotenv file includes all necessary sections and information, following best practices
-  No sensitive  information  is Pushed
