### ISSUE TITLE
Database Integration

### ISSUE THREAD

**Issue by bertrandshema** [atlp-rwanda/dynamites-ecomm-be#16]
## Description
Here, I will set up TypeORM with PostgreSQL for our e-commerce application and define entity models to represent all the data of the application

## Tasks
- [x] Set up TypeORM for database integration
- [x] Configure TypeORM with PostgreSQL
- [x] Define the User entity models for the e-commerce

## Related Issues
#5 

## Definition of Done
- TypeORM is installed successfully
- Database is connected successfully
- Database check endpoints working

**Comment by Habinezajanvier** [comment]
@bertrandshema , we are not using Prisma but typeORM
