### ISSUE TITLE
Set up Continuous Integration (CI/CD) Pipeline

### ISSUE THREAD

**Issue by niyibi250** [atlp-rwanda/dynamites-ecomm-be#17]
### Description

Implement Continuous Integration (CI) and Continuous Deployment (CD) for the ecomm-be project to automate testing, linting, building, and API deployment processes.

### Tasks

- [x] Set up a CI pipeline (GitHub Actions)
- [x] Configure the CI pipeline to run tests, lint, and build the project
- [x] Deploy the API

### Developer Note

- In this CI we will use git action due to its flexible and it provide well labeled error messages and it is well understand.
- Also, for node that will be used we will use node latest version.
- for install dependencies we will use `npm ci` because its smooth and faster than `npm install`
- the CI will be run when Developer try to push code.
