### ISSUE TITLE
Issue: Linting Errors Causing CI Actions to Fail

### ISSUE THREAD

**Issue by niyobern** [atlp-rwanda/dynamites-ecomm-be#43]
### Summary

Our Continuous Integration (CI) actions are currently failing due to linting errors in our codebase. The primary issues are the use of `console.log` statements and the use of `any` and `Function` as types, which our linter (ESLint) is configured to flag as errors and warnings.

### Example

An example of this issue can be seen in the `errorHandler.ts` file:

```typescript
function errorHandler(func: Function) {
    return async (req: Request, res: Response, next: NextFunction) => {
      try {
        await func(req, res, next);
      } catch (error: any) {
        console.log({ error });
        const message = error.detail || 'Internal Server Error';
        res.status(500).send(message);
      }
    };
}
```

### Expected Behavior

Our CI actions should pass successfully, with no linting errors or warnings.

### Proposed Solution

1. Replace all `console.log ` statements with a dedicated logging handler that can has been defined in the last milestone. This will prevent unnecessary console logging in production and will also resolve the linting warnings.
2. Replace the `Function` type with a more specific function type that accurately describes the expected parameters and return type.
3. Replace the `any` type with a more specific type.

### Tasks

- [ ]  Identify all instances of console.log in the codebase and replace them with calls to a logging handler.
- [ ]  Replace the `Function` type in `errorHandler.ts` with a more specific function type.
- [ ] Replace the `any` type in `errorHandler.ts` with a more specific type or `unknown`.
- [ ] Verify that all linting errors and warnings are resolved and that the CI actions pass successfully.

#### Additional Context

Resolving this issue will improve the reliability of our CI actions and will help to maintain high code quality standards in our codebase.
