### ISSUE TITLE
Feat: Buyer should be able view specific product

### ISSUE THREAD

**Issue by mukunzidd** [atlp-rwanda/dynamites-ecomm-be#54]
---
### Description

As a buyer, I want to be able to view a specific product, so as to obtain more information about it

### Tasks

- [x] Implement a get product API endpoint
- [x] Implement appropriate error handling and responses
- [x] Write appropriate unit tests
- [x] Write appropriate documentation for the resulting endpoint 

### Related Issues

- #37 

### Definition of Done

- Buyer can retrieve a specific product
- Unit tests are written and passing
- Code adheres to coding standards and best practices
- API documentation for the resulting endpoint is completed

**Comment by jkarenzi** [comment]
## Implementation plan

### 1. Deliverables at the end of the week:

- Implement an API endpoint where buyer can retrieve a specific product
- Write appropriate swagger documentation for new endpoints created
- Implement appropriate error handling and responses
- Write comprehensive unit tests


### 2. Data Flow / Flowchart / Pseudocode / ERD Diagrams:
<img width="672" alt="buyer view specific product" src="https://github.com/atlp-rwanda/dynamites-ecomm-be/assets/109604986/058c7251-4fde-42f9-a1a2-50f648f76216">


### 3. Schedule of Implementation of Various Parts:

**Day 1: Saturday (11/05/2024)**

- Implement an API endpoint where buyer can retrieve a specific product
- Implement appropriate error handling and responses

**Day 2: Sunday (12/05/2024)**

- Write appropriate swagger documentation for new endpoints created
- Write comprehensive unit tests

### 4.Related tasks
#37 

###   5. External services or libraries to be used.
