### ISSUE TITLE
Feat: Buyer should be able to list products from vendors

### ISSUE THREAD

**Issue by mukunzidd** [atlp-rwanda/dynamites-ecomm-be#57]
### Description
This feature will allow buyers to view the list of products offered by vendors on the platform. This feature enhances the browsing experience for buyers, allowing them to explore available products easily.

### Functionality:

- [ ] -  Buyers can go to a page showing all products from the seller.
- [ ] -  Each product listing includes basic information like name and price.
- [ ] - Add pagination to data from database

### Acceptance Criteria:

-  Buyers can easily access the page showing all the seller's products.
-  The page shows the correct info for all products.
-  pagination work properly.
-  If Something goes wrong, buyers get a helpful error message

### Related Issues
https://github.com/atlp-rwanda/dynamites-ecomm-be/issues/37

### Definition of Done:

- The API endpoint for product listings is implemented and functional.
- Product listings display accurate information.
- pagination is working.
- Unit tests ensure functionality is reliable.
- The codebase follows coding standards and best practices.

**Comment by niyibi250** [comment]
### Implementation plan
### 1. Deliverables at the end of the week:

1. Implement an API endpoint where buyer can retrieve a products
2. implement pagination on data retrieved
3. Write appropriate swagger documentation for new endpoints created
4. Implement appropriate error handling and responses
5. Write comprehensive unit tests

### 2. Data Flow / Flowchart / Pseudocode / ERD Diagrams:



### 3. Schedule of Implementation of Various Parts:
### Day 1: Saturday (11/05/2024)

- Implement an API endpoint where buyer can retrieve a products
- Implement appropriate error handling and responses
### Day 2: Sunday (12/05/2024)

- implement the pagination on data
- Write appropriate swagger documentation for new endpoints created
- Write comprehensive unit tests

### 4.Related tasks
https://github.com/atlp-rwanda/dynamites-ecomm-be/issues/37

### 5. External services or libraries to be used.
