### ISSUE TITLE
Feat: Buyer should be able to manage a wishlist

### ISSUE THREAD

**Issue by mukunzidd** [atlp-rwanda/dynamites-ecomm-be#58]
# User Story: Buyer should be able to manage a wishlist

## Description

As a buyer, i want to view The wishlist management feature enables buyers to create, organize, and maintain a list of desired items they wish to purchase in the future. This provides users with a convenient way to keep track of products they are interested in.

### Acceptance Criteria

- [ ] Buyers can  add products to their wishlist from product pages or search results. 
- [ ] Buyers can view their wishlist at any time to see all the items they have saved. 
- [ ] Buyer can  remove  item from wish list 
- [ ] When buyers are ready to make a purchase, they can easily move items from their wishlist to the shopping cart.

## Developer Notes

- Design and implement the data model for the wishList
- Define the API endpoints and request/response payloads for cart operations
- Integrate with the product catalog service to fetch product details and validate item availability
- Handle edge cases such as out-of-stock items, removed products, or pricing changes
- Implement Validations of product wish List 

## Related Issues

- #37 (Product  CRUD)
- #56 (Product search)

**Comment by 13XAVI** [comment]
# Implementation Plan
## 1. Deliverables at the end of the week:
- Design and implement the data model for the wishList
- Define the API endpoints and request/response payloads for cart operations
- Integrate with the product catalog service to fetch product details and validate item availability
- Handle edge cases such as out-of-stock items, removed products, or pricing changes
- Implement Validations of product wish List 
- Write comprehensive unit tests
- Document Each end Points
##  2. Data Flow 
- Flowchart 

![erwish drawio](https://github.com/atlp-rwanda/dynamites-ecomm-be/assets/101405347/ea353a65-1473-4276-a8b7-37fe26385027)

- ERD Diagrams:

![Er drawio](https://github.com/atlp-rwanda/dynamites-ecomm-be/assets/101405347/18cd3785-2bd8-4566-b866-2d09afbd3362)

## 3. Schedule of Implementation of Various Parts:
### Day 1: Monday (14/05/2024)
- Design and implement the data model for the wishList
- Define the API endpoints and request/response payloads for cart operations
### Day 2: Tuesday (15/05/2024)
- Write comprehensive unit tests for All End Points
- Document Each end Points
## 4.Related tasks
#37 (Manage Product )
#56 (Search Product)
