### ISSUE TITLE
Feat: Guest/Buyer should be able to add items to cart

### ISSUE THREAD

**Issue by jkarenzi** [atlp-rwanda/dynamites-ecomm-be#77]
---
### Description

As a buyer, I want to be able to add or remove one or more items/products to or from my cart

### Tasks

- [x] Implement an endpoint where a buyer can add new items to their cart
- [x] Implement an endpoint where a buyer can remove existing items from their cart
- [x] Implement appropriate error handling and responses
- [x] Write appropriate unit tests
- [x] Write appropriate documentation for the resulting endpoints

### Definition of Done

- Buyers can add and remove items from their cart as they wish
- Unit tests are written and passing
- Code adheres to coding standards and best practices
- API documentation for the resulting endpoint is completed

**Comment by jkarenzi** [comment]
## Implementation plan for our task:

### 1. Deliverables at the end of the week:

 - [x] Implement an endpoint where a buyer can add new items to their cart
 - [x] Implement an endpoint where a buyer can remove existing items from their cart
 - [x] Implement appropriate error handling and responses
 - [x] Write appropriate unit tests
 - [x] Write appropriate documentation for the resulting endpoints

### 2. Data Flow / Flowchart / Pseudocode / ERD Diagrams:
![Flowchart](https://github.com/atlp-rwanda/dynamites-ecomm-be/assets/109604986/b3bc511f-8bbb-44a4-8f83-6c08933e032c)



### 3. Schedule of Implementation of Various Parts:

**Day 1: Tuesday (21/05/2024)**

- Design the database schema for cart.
- Implement endpoints for adding, getting and removing items from the cart

**Day 2: Wednesday (22/05/2024)**

- Write all appropriate unit tests
- Write appropriate swagger documentation for new endpoints
