### ISSUE TITLE
Set up a testing framework (e.g., Jest & Supertest)

### ISSUE THREAD

**Issue by ambroisegithub** [atlp-rwanda/dynamites-ecomm-be#8]
#### Description

As a developer, I want to set test runner so that when we are adding test, we will not need to re-configure the runner again.

#### Tasks

- [X] Add jest and it's types
- [X] Separate testing db from development db
- [X] Configure jest as our test runner
- [ ] Add supper for testing endpoints

#### Developer Notes

- Make sure test runs on every environment i.e windows, Mac and linux
- Make sure that coverage is added
- Make sure that development/production database will not be corrupted with test data

#### Related Issues

- #5 
- #4 

#### Definition of Done
- Tests running with coverage
