### ISSUE TITLE
Feat:  Buyer should be able to provide a review

### ISSUE THREAD

**Issue by Dawaic6** [atlp-rwanda/dynamites-ecomm-be#89]
---
### Description

As a buyer, I can submit reviews after receiving a product.

### Tasks

- [x] Create   database model for review  
- [x] Implement an endpoint of posting a review and  updating the product's average rating.
- [x] Implement validation checks  to ensure that reviews meet certain  criteria. and Restrict 
         who can submit review likebuyer must be authorized  
- [x] Write appropriate unit tests
- [x] Write swagger documentation for the resulting endpoints

### Related Issues

#83 

### Definition of Done
- Endpoint of posting a review and  updating the product's average rating.
- Database model for review 
- Unit tests are written and passing
- Swagger documentation

**Comment by Dawaic6** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-420fcb38-7fff-9502-e4f7-23f873738d91"><h2 dir="ltr" style="line-height:1.38;margin-top:18pt;margin-bottom:6pt;"><span style="font-size:16pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">#1. Deliverables at the end of the project.</span></h2><p dir="ltr" style="line-height:1.7999999999999998;margin-left: 36pt;margin-right: -11pt;background-color:#ffffff;margin-top:0pt;margin-bottom:12pt;padding:1.5pt 11.25pt 1.5pt 0pt;"><br /></p><div dir="ltr" style="margin-left:0pt;" align="left">
- Endpoint of submitting a review and updating the product's average rating.- Database model for review - Unit tests are written and passing- Swagger documentation
--


</div><h2 dir="ltr" style="line-height:1.38;margin-top:18pt;margin-bottom:6pt;"><span style="font-size:16pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">#2. Data flow / Flowchart / pseudocode / ERD diagrams</span></h2><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;&nbsp;&nbsp;#ERD&nbsp; diagram</span></p><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;&nbsp;</span><span style="font-size:11pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:624px;height:291px;"><img src="https://lh7-us.googleusercontent.com/LCiCBy4w6gfKavq_NNsxfni1F-QY04DkPppreMNufN9niqW2RFFxp5GKi2xuStL-uNolXRGdWj9E9k1GuFA2Z1VL63KTdRiXruIIhRoTFTu49gdsQ0DorGO4XliBa6VsZr_VUfkxwxzX5VmlM43cBaA" width="624" height="291" style="margin-left:0px;margin-top:0px;" /></span></span></p><br /><br /><br /><br /><br /><br /><br /><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"># Flowchart</span></p><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:624px;height:251px;"><img src="https://lh7-us.googleusercontent.com/Zxy-kaGBW6ysavNjssu-ynpFnow7VxEAJMEg8fgF5GSKc5rHOfnHN2CH1ftxm19eX_TRsy-nbKcLhYZcGZ7bXHxVbRSS0p8ic6O-VCsH8hxfCYPDAiphbUmSne0LsLuHSrrn3Xen0BHLl0bG5evPk4w" width="624" height="251" style="margin-left:0px;margin-top:0px;" /></span></span></p><br /><br /><h2 dir="ltr" style="line-height:1.38;margin-top:18pt;margin-bottom:6pt;"><span style="font-size:16pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">#3. Schedule of implementation of the various parts</span></h2><p dir="ltr" style="line-height:1.7999999999999998;background-color:#ffffff;margin-top:3pt;margin-bottom:0pt;padding:1.5pt 11.25pt 1.5pt 0pt;"><span style="font-size:10.5pt;font-family:Arial,sans-serif;color:#1f2328;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">#Friday (24th/May/2024)</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.7999999999999998;background-color:#ffffff;margin-top:3pt;margin-bottom:0pt;padding:1.5pt 11.25pt 1.5pt 0pt;" role="presentation"><span style="font-size:10.5pt;font-family:Arial,sans-serif;color:#1f2328;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;Finish endpoint where&nbsp; buyer can post a review ,updating the product's average rating.</span></p></li></ul><p dir="ltr" style="line-height:1.7999999999999998;background-color:#ffffff;margin-top:3pt;margin-bottom:0pt;padding:1.5pt 11.25pt 1.5pt 0pt;"><span style="font-size:10.5pt;font-family:Arial,sans-serif;color:#1f2328;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">#Monday (27th/May/2024)</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:10.5pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.7999999999999998;background-color:#ffffff;margin-top:3pt;margin-bottom:0pt;padding:1.5pt 11.25pt 1.5pt 0pt;" role="presentation"><span style="font-size:10.5pt;font-family:Arial,sans-serif;color:#1f2328;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;Unit test&nbsp; which passing</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:10.5pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.7999999999999998;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:1.5pt 11.25pt 1.5pt 0pt;" role="presentation"><span style="font-size:10.5pt;font-family:Arial,sans-serif;color:#1f2328;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Complete swagger document&nbsp; for search endpoint&nbsp;</span></p></li></ul><p dir="ltr" style="line-height:1.7999999999999998;background-color:#ffffff;margin-top:3pt;margin-bottom:0pt;padding:1.5pt 11.25pt 1.5pt 0pt;"><span style="font-size:11.5pt;font-family:Arial,sans-serif;color:#1d1c1d;background-color:#f8f8f8;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">#Tuesday (28/may/2024)</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11.5pt;font-family:Arial,sans-serif;color:#1d1c1d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.7999999999999998;background-color:#ffffff;margin-top:3pt;margin-bottom:0pt;padding:1.5pt 11.25pt 1.5pt 0pt;" role="presentation"><span style="font-size:11.5pt;font-family:Arial,sans-serif;color:#1d1c1d;background-color:#f8f8f8;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;Finish task&nbsp;</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11.5pt;font-family:Arial,sans-serif;color:#1d1c1d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.7999999999999998;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:1.5pt 11.25pt 1.5pt 0pt;" role="presentation"><span style="font-size:11.5pt;font-family:Arial,sans-serif;color:#1d1c1d;background-color:#f8f8f8;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">And tracking another issue to be fixed</span></p></li></ul><p dir="ltr" style="line-height:1.7999999999999998;margin-left: 36pt;background-color:#ffffff;margin-top:3pt;margin-bottom:0pt;padding:1.5pt 11.25pt 1.5pt 0pt;"><br /></p><h2 dir="ltr" style="line-height:1.38;margin-top:18pt;margin-bottom:6pt;"><span style="font-size:16pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">#4. Dependencies/Foreseen blockers from team members</span></h2><br /><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">#83</span></p></li></ul></b>
</body>
</html>
