### ISSUE TITLE
Feature: Order Tracking for Vendor and Buyer

### ISSUE THREAD

**Issue by bertrandshema** [atlp-rwanda/dynamites-ecomm-be#91]
This PR adds a feature to track the order for the vendor and the buyer.

## Definition of Done
- [x] After a buyer makes a checkout update the order status to **Pending**
- [x] When the payment fails due to a response from the payment gateway update the status to **Failed**
- [x] When the user abandons the payment gateway without paying update the status to **Cancelled** 
- [x] When the client makes a payment update the status to **Paid**
- [x] When the Vendor starts the shipping process update status to **Shipping**
- [x] When the product has been delivered to the destination change the status to **Delivered**
- [x] If the buyer requests a return change the status to **Returned**
- [x] If there are return requests from the buyer within 24 hours from the delivery time update the status to **Completed**

## Related Issues:
#77 
#79 
#81

**Comment by bertrandshema** [comment]
## Implementation Plan

### Tasks
- [ ] Implements endpoints of all features
- [ ] Write controllers to manage all features
- [ ] Write all appropriate unit tests
- [ ] Write appropriate swagger documentation for new endpoints

### Flowchart
![Flowcart](https://github.com/atlp-rwanda/dynamites-ecomm-be/assets/51314498/0d7f6d44-fb34-4121-88da-63003e5bcdf4)

### Timeline
Day 1: Friday  (24/05/2024)
1. Implements endpoints of all tasks
2. Write controllers to manage all features

Day 2: Saturday (26/05/2024)
1. Write all appropriate unit tests
2. Write appropriate swagger documentation for new endpoints
